"use client";

import React, { useState, useEffect } from 'react';
import { createClient } from '@/lib/supabase';
import { 
  Ticket, 
  Search, 
  Filter, 
  Calendar, 
  Users, 
  TrendingUp, 
  ToggleLeft, 
  ToggleRight,
  Loader2,
  ChevronRight,
  Zap,
  ExternalLink,
  UserCheck,
  Trash2
} from 'lucide-react';
import { motion } from 'framer-motion';
import { formatPrice } from '@/lib/utils';
import Link from 'next/link';

export default function AdminMarketerCouponsPage() {
  const [coupons, setCoupons] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filter, setFilter] = useState('all');
  
  const supabase = createClient();

  useEffect(() => {
    fetchCoupons();
  }, []);

  const fetchCoupons = async () => {
    setLoading(true);
    
    // 1. Fetch Marketer Coupons with Marketer Details
    const { data: marketerCoupons } = await supabase
      .from('skin_marketer_coupons')
      .select('*, skin_marketers(skin_name, skin_email), skin_marketer_commissions(count)')
      .order('skin_created_at', { ascending: false });

    setCoupons(marketerCoupons || []);
    setLoading(false);
  };

  const toggleCouponStatus = async (id: string, currentStatus: boolean) => {
    const { error } = await supabase
      .from('skin_marketer_coupons')
      .update({ skin_is_active: !currentStatus })
      .eq('skin_id', id);
    
    if (!error) {
      setCoupons(coupons.map(c => c.skin_id === id ? { ...c, skin_is_active: !currentStatus } : c));
    }
  };

  const deleteMarketerCoupon = async (id: string) => {
    if (!window.confirm('CRITICAL: Delete this affiliate code permanently?')) return;
    
    const { error } = await supabase
      .from('skin_marketer_coupons')
      .delete()
      .eq('skin_id', id);

    if (!error) {
      setCoupons(prev => prev.filter(c => c.skin_id !== id));
    } else {
      alert('Error deleting coupon: ' + error.message);
    }
  };

  const filteredCoupons = coupons.filter(c => {
    const matchesSearch = 
        c.skin_code.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (c.skin_marketers?.skin_name || '').toLowerCase().includes(searchTerm.toLowerCase());
    const matchesFilter = filter === 'all' || (filter === 'active' ? c.skin_is_active : !c.skin_is_active);
    return matchesSearch && matchesFilter;
  });

  const stats = [
    { label: 'Active Codes', value: coupons.filter(c => c.skin_is_active).length, icon: <Zap className="text-accent-gold" />, bg: 'bg-accent-gold/10' },
    { label: 'Total Partners', value: new Set(coupons.map(c => c.skin_marketer_id)).size, icon: <UserCheck className="text-blue-600" />, bg: 'bg-blue-50' },
    { label: 'Total Attribution', value: coupons.reduce((acc, c) => acc + (c.skin_marketer_commissions?.[0]?.count || 0), 0), icon: <TrendingUp className="text-green-600" />, bg: 'bg-green-50' },
    { label: 'Avg Discount', value: '10%', icon: <Ticket className="text-purple-600" />, bg: 'bg-purple-50' },
  ];

  return (
    <div className="space-y-10 pb-20">
      <header className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div>
          <h1 className="text-4xl font-black text-text-dark tracking-tighter uppercase italic">Affiliate Coupons</h1>
          <p className="text-text-muted text-xs mt-2 font-medium italic">Monitor and govern discount codes generated by your marketing partners.</p>
        </div>
        <Link 
          href="/admin/marketer-coupons/usage"
          className="h-14 px-8 rounded-full bg-text-dark text-white font-black text-xs tracking-widest uppercase flex items-center gap-3 hover:bg-accent-gold transition-all shadow-xl"
        >
          <TrendingUp size={18} /> View Detailed Logs
        </Link>
      </header>

      {/* Stats Summary */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <motion.div 
            key={i}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className={`p-8 rounded-[2.5rem] border border-secondary-ivory shadow-sm ${stat.bg}`}
          >
            <div className="flex items-center gap-4 mb-4">
              <div className="p-3 bg-white rounded-2xl shadow-sm">{stat.icon}</div>
              <p className="text-[10px] font-black uppercase tracking-widest text-text-muted">{stat.label}</p>
            </div>
            <p className="text-3xl font-black text-text-dark">{stat.value}</p>
          </motion.div>
        ))}
      </div>

      {/* Control Bar */}
      <div className="flex flex-col md:flex-row gap-4 bg-white p-6 rounded-[2.5rem] border border-secondary-ivory shadow-sm">
        <div className="relative flex-1">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-text-muted" size={18} />
          <input 
            type="text" 
            placeholder="Search by code or partner name..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full h-14 bg-secondary-ivory/50 border-none rounded-xl pl-12 pr-4 text-xs font-bold uppercase tracking-widest focus:ring-2 focus:ring-accent-gold outline-none"
          />
        </div>
        <div className="flex items-center gap-4">
          <Filter size={18} className="text-text-muted" />
          <select 
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            className="h-14 bg-secondary-ivory/50 border-none rounded-xl px-8 text-[10px] font-black uppercase tracking-widest focus:ring-2 focus:ring-accent-gold outline-none cursor-pointer"
          >
            <option value="all">ALL CODES</option>
            <option value="active">ACTIVE ONLY</option>
            <option value="inactive">PAUSED ONLY</option>
          </select>
        </div>
      </div>

      {/* Coupons Table */}
      <div className="bg-white border border-secondary-ivory rounded-[3.5rem] shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-secondary-ivory bg-secondary-ivory/30">
                <th className="px-10 py-8 text-[10px] font-black uppercase tracking-widest text-text-muted">Referral Code</th>
                <th className="px-10 py-8 text-[10px] font-black uppercase tracking-widest text-text-muted">Marketing Partner</th>
                <th className="px-10 py-8 text-[10px] font-black uppercase tracking-widest text-text-muted">Usage Status</th>
                <th className="px-10 py-8 text-[10px] font-black uppercase tracking-widest text-text-muted">Discount</th>
                <th className="px-10 py-8 text-[10px] font-black uppercase tracking-widest text-text-muted">Expiry</th>
                <th className="px-10 py-8 text-[10px] font-black uppercase tracking-widest text-text-muted">Status</th>
                <th className="px-10 py-8 text-[10px] font-black uppercase tracking-widest text-text-muted text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-secondary-ivory">
              {loading ? (
                <tr><td colSpan={7} className="py-32 text-center"><Loader2 className="animate-spin inline-block text-accent-gold" size={40} /></td></tr>
              ) : filteredCoupons.length > 0 ? (
                filteredCoupons.map((coupon) => {
                  const usageCount = coupon.skin_marketer_commissions?.[0]?.count || 0;
                  return (
                    <tr key={coupon.skin_id} className="hover:bg-secondary-ivory/5 transition-colors group">
                      <td className="px-10 py-8">
                        <div className="flex items-center gap-5">
                          <div className="w-14 h-14 rounded-2xl bg-text-dark flex items-center justify-center text-white shadow-xl group-hover:bg-accent-gold transition-all duration-500">
                            <Zap size={20} />
                          </div>
                          <div>
                            <p className="font-black text-text-dark text-lg tracking-[0.2em] uppercase">{coupon.skin_code}</p>
                            <p className="text-[9px] text-text-muted font-black uppercase mt-1">Marketer Generated</p>
                          </div>
                        </div>
                      </td>
                      <td className="px-10 py-8">
                        <div className="flex flex-col">
                           <p className="text-sm font-black text-text-dark uppercase tracking-tight">{coupon.skin_marketers?.skin_name || 'Unknown Partner'}</p>
                           <p className="text-[9px] text-text-muted font-bold lowercase tracking-normal">{coupon.skin_marketers?.skin_email}</p>
                        </div>
                      </td>
                      <td className="px-10 py-8">
                        <div className={`flex flex-col gap-1 px-4 py-2 rounded-2xl w-fit ${usageCount > 0 ? 'bg-green-50 text-green-600 border border-green-100' : 'bg-gray-50 text-gray-400 border border-gray-100'}`}>
                          <span className="text-[9px] font-black uppercase tracking-widest">{usageCount > 0 ? 'Used' : 'Never Used'}</span>
                          <span className="text-[8px] font-bold italic">{usageCount} Redemptions</span>
                        </div>
                      </td>
                      <td className="px-10 py-8">
                        <p className="font-black text-text-dark text-xl">
                          {coupon.skin_discount_percent}% <span className="text-[10px] text-text-muted">OFF</span>
                        </p>
                      </td>
                      <td className="px-10 py-8">
                        <div className="flex items-center gap-2 text-[10px] font-black text-text-dark uppercase tracking-widest italic">
                          <Calendar size={14} className="text-accent-gold" />
                          {coupon.skin_expiry_date ? new Date(coupon.skin_expiry_date).toLocaleDateString() : 'NO EXPIRY'}
                        </div>
                      </td>
                      <td className="px-10 py-8">
                         <button 
                           onClick={() => toggleCouponStatus(coupon.skin_id, coupon.skin_is_active)}
                           className={`flex items-center gap-2 px-4 py-2 rounded-full text-[9px] font-black uppercase tracking-widest transition-all ${
                             coupon.skin_is_active ? 'bg-green-50 text-green-600' : 'bg-red-50 text-red-600'
                           }`}
                         >
                           {coupon.skin_is_active ? <><ToggleRight size={16} /> Live</> : <><ToggleLeft size={16} /> Paused</>}
                         </button>
                      </td>
                      <td className="px-10 py-8 text-right">
                        <div className="flex items-center justify-end gap-3">
                          <Link 
                            href={`/admin/orders?search=${coupon.skin_code}`}
                            className="p-3 bg-secondary-ivory rounded-xl text-text-muted hover:text-accent-gold hover:bg-white hover:shadow-lg transition-all"
                            title="View Linked Orders"
                          >
                            <ExternalLink size={20} />
                          </Link>
                          <Link 
                            href={`/admin/marketers`} // Or deep link to marketer edit
                            className="p-3 bg-secondary-ivory rounded-xl text-text-muted hover:text-text-dark hover:bg-white hover:shadow-lg transition-all"
                            title="Manage Partner"
                          >
                            <Users size={20} />
                          </Link>
                          {usageCount === 0 && (
                            <button 
                              onClick={() => deleteMarketerCoupon(coupon.skin_id)}
                              className="p-3 bg-red-50 text-red-500 rounded-xl hover:bg-red-500 hover:text-white transition-all shadow-sm"
                              title="Delete Unused Code"
                            >
                              <Trash2 size={20} />
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td colSpan={7} className="py-32 text-center">
                    <div className="w-20 h-20 bg-secondary-ivory/30 rounded-full flex items-center justify-center mx-auto mb-6">
                       <Zap className="text-secondary-ivory" size={40} />
                    </div>
                    <h3 className="text-xl font-black text-text-dark uppercase italic">No Affiliate Codes</h3>
                    <p className="text-text-muted mt-2 font-medium italic">Marketer generated codes will appear here once they start creating campaigns.</p>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
